[project]
authors = ["EX-DENGJIE035 <EX-DENGJIE035@pingan.com.cn>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "ntruprime"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.6.0,<25"
python = "==3.9"
pytorch = ">=2.4.1,<3"
